server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hhn004460
    url: jdbc:mysql://localhost:3306/crud
  thymeleaf:
    cache: false
